# Generated by Django 3.1.6 on 2021-04-12 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210410_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 4, 12)),
        ),
    ]
