# Generated by Django 3.1.6 on 2021-04-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20210414_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.topic'),
        ),
    ]
