# Generated by Django 3.1.6 on 2021-04-15 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_auto_20210414_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 4, 15)),
        ),
    ]
