# Generated by Django 3.1.6 on 2021-04-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_auto_20210415_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file_field',
        ),
    ]
