# Generated by Django 3.1.6 on 2021-04-15 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20210415_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photos', to='boards.topic'),
        ),
    ]
