# Generated by Django 3.1.6 on 2021-04-16 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_auto_20210415_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 4, 16)),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='static/img/'),
        ),
    ]
