# Generated by Django 3.2 on 2021-04-19 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0015_boardaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 4, 19)),
        ),
    ]
